In [3]:
import pandas as pd

In [12]:
instancesHeader = ['GRAPH', 'SOURCE', 'TARGET', 'K']

instancesDf = pd.read_csv('randomInst.csv', delimiter=' ', header=None, names=instancesHeader)
instancesDf['GRAPH'] = instancesDf['GRAPH'].apply(lambda x: x.split('/')[-1])
instancesDf

                                    GRAPH  SOURCE  TARGET     K
0                  random_gnm_2000_2_1.gr       0    1999   200
1                  random_gnm_2000_3_1.gr       0    1999   200
2                  random_gnm_2000_4_1.gr       0    1999   200
3                  random_gnm_2000_7_1.gr       0    1999   200
4                 random_gnm_2000_10_1.gr       0    1999   200
...                                   ...     ...     ...   ...
7195  random_connected_gnm_10000_10_20.gr       0    9999  2000
7196  random_connected_gnm_10000_20_20.gr       0    9999  2000
7197  random_connected_gnm_10000_30_20.gr       0    9999  2000
7198  random_connected_gnm_10000_40_20.gr       0    9999  2000
7199  random_connected_gnm_10000_50_20.gr       0    9999  2000

[7200 rows x 4 columns]

In [16]:
newAlgoHeader = ['ALGO', 'GRAPH', 'SOURCE', 'TARGET', 'K', 'TIME', 'COST_MIN', 'COST_MAX', 'SOLUTIONS', 'BDA_QUERIES', 'FAILED_BDA', 'EXPANSIONS_PER_BDA', 'EXPANSIONS_PER_FAILED_BDA', 'POOL_SIZE']

newAlgoDf = pd.read_csv('finalRandomResults_na.csv', delimiter=';', header=None, names=newAlgoHeader)
newAlgoDf

,ALGO,GRAPH,SOURCE,TARGET,K,TIME,COST_MIN,COST_MAX,SOLUTIONS,BDA_QUERIES,FAILED_BDA,EXPANSIONS_PER_BDA,EXPANSIONS_PER_FAILED_BDA,POOL_SIZE
0,NaN,random_gnm_2000_7_1.gr,0,1999,200,0.017,308012,503690,200,397,110,18,9,200
1,NaN,random_gnm_2000_10_1.gr,0,1999,200,0.010,194138,290856,200,397,110,14,7,200
2,NaN,random_gnm_2000_20_1.gr,0,1999,200,0.009,84540,150903,200,397,115,14,7,800
3,NaN,random_gnm_2000_30_1.gr,0,1999,200,0.008,73022,104070,200,397,108,14,8,400
4,NaN,random_gnm_2000_40_1.gr,0,1999,200,0.008,42072,80557,200,397,103,13,7,600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,NaN,random_connected_gnm_10000_10_20.gr,0,9999,2000,0.054,187052,364681,2000,3997,1154,16,8,200
5440,NaN,random_connected_gnm_10000_20_20.gr,0,9999,2000,0.050,107753,197586,2000,3996,1168,17,8,400
5441,NaN,random_connected_gnm_10000_30_20.gr,0,9999,2000,0.061,67688,117669,2000,3997,1141,17,9,600
5442,NaN,random_connected_gnm_10000_40_20.gr,0,9999,2000,0.076,45714,89003,2000,3923,1097,19,10,1400
5443,NaN,random_connected_gnm_10000_50_20.gr,0,9999,2000,0.090,33340,67920,2000,3953,1126,19,10,1600

In [14]:
kurzHeader = ['ALGO', 'OPTIMISTIC', 'DUMMY' ,'PRUNING', 'GRAPH', 'NODES', 'ARCS', 'SOURCE' , 'TARGET', 'K', 'SOLUTIONS', 'COST_MIN', 'COST_MAX', 'SUM_OF_COSTS', 'SP_TREES', 'SP_TREES_EXPANSIONS', 'TIME']

kurzDf = pd.read_csv('finalRandomResults_kurz.csv', delimiter=';', header=None, names=kurzHeader)
kurzDf = kurzDf.loc[kurzDf['SOLUTIONS'] > 1]
kurzDf

,ALGO,OPTIMISTIC,DUMMY,PRUNING,GRAPH,NODES,ARCS,SOURCE,TARGET,K,SOLUTIONS,COST_MIN,COST_MAX,SUM_OF_COSTS,SP_TREES,SP_TREES_EXPANSIONS,TIME
3,kurz,optimistic,NaN,distance-pruning,random_gnm_2000_7_1.gr,2000,7000,0,1999,200,200,308012,503690,95064916,8,7054,0.010
4,kurz,optimistic,NaN,distance-pruning,random_gnm_2000_10_1.gr,2000,10000,0,1999,200,200,194138,290856,54428664,3,4091,0.006
5,kurz,optimistic,NaN,distance-pruning,random_gnm_2000_20_1.gr,2000,20000,0,1999,200,200,84540,150903,28120108,3,5990,0.009
6,kurz,optimistic,NaN,distance-pruning,random_gnm_2000_30_1.gr,2000,30000,0,1999,200,200,73022,104070,19523147,3,4377,0.014
7,kurz,optimistic,NaN,distance-pruning,random_gnm_2000_40_1.gr,2000,40000,0,1999,200,200,42072,80557,15158898,18,10344,0.018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7195,kurz,optimistic,NaN,distance-pruning,random_connected_gnm_10000_10_20.gr,10000,50000,0,9999,2000,2000,187052,364681,687033993,19,78908,0.075
7196,kurz,optimistic,NaN,distance-pruning,random_connected_gnm_10000_20_20.gr,10000,100000,0,9999,2000,2000,107753,197586,374945349,31,126256,0.105
7197,kurz,optimistic,NaN,distance-pruning,random_connected_gnm_10000_30_20.gr,10000,150000,0,9999,2000,2000,67688,117669,222079469,31,103495,0.114
7198,kurz,optimistic,NaN,distance-pruning,random_connected_gnm_10000_40_20.gr,10000,200000,0,9999,2000,2000,45714,89003,168192527,28,108689,0.142
7199,kurz,optimistic,NaN,distance-pruning,random_connected_gnm_10000_50_20.gr,10000,250000,0,9999,2000,2000,33340,67920,128071165,44,148950,0.175

In [19]:
mergedDf = pd.merge(instancesDf, newAlgoDf, on=['GRAPH', 'SOURCE', 'TARGET', 'K'], how='right')
mergedDf = pd.merge(mergedDf, kurzDf, on=['GRAPH', 'SOURCE', 'TARGET', 'K'], how='left', suffixes=("_na", "_kurz"))
#mergedDf = mergedDf.loc[mergedDf['TIME_kurz'].notna() | mergedDf['TIME_na'].notna()]
mergedDf

,GRAPH,SOURCE,TARGET,K,ALGO_na,TIME_na,COST_MIN_na,COST_MAX_na,SOLUTIONS_na,BDA_QUERIES,...,PRUNING,NODES,ARCS,SOLUTIONS_kurz,COST_MIN_kurz,COST_MAX_kurz,SUM_OF_COSTS,SP_TREES,SP_TREES_EXPANSIONS,TIME_kurz
0,random_gnm_2000_7_1.gr,0,1999,200,NaN,0.017,308012,503690,200,397,...,distance-pruning,2000,7000,200,308012,503690,95064916,8,7054,0.010
1,random_gnm_2000_10_1.gr,0,1999,200,NaN,0.010,194138,290856,200,397,...,distance-pruning,2000,10000,200,194138,290856,54428664,3,4091,0.006
2,random_gnm_2000_20_1.gr,0,1999,200,NaN,0.009,84540,150903,200,397,...,distance-pruning,2000,20000,200,84540,150903,28120108,3,5990,0.009
3,random_gnm_2000_30_1.gr,0,1999,200,NaN,0.008,73022,104070,200,397,...,distance-pruning,2000,30000,200,73022,104070,19523147,3,4377,0.014
4,random_gnm_2000_40_1.gr,0,1999,200,NaN,0.008,42072,80557,200,397,...,distance-pruning,2000,40000,200,42072,80557,15158898,18,10344,0.018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,random_connected_gnm_10000_10_20.gr,0,9999,2000,NaN,0.054,187052,364681,2000,3997,...,distance-pruning,10000,50000,2000,187052,364681,687033993,19,78908,0.075
5440,random_connected_gnm_10000_20_20.gr,0,9999,2000,NaN,0.050,107753,197586,2000,3996,...,distance-pruning,10000,100000,2000,107753,197586,374945349,31,126256,0.105
5441,random_connected_gnm_10000_30_20.gr,0,9999,2000,NaN,0.061,67688,117669,2000,3997,...,distance-pruning,10000,150000,2000,67688,117669,222079469,31,103495,0.114
5442,random_connected_gnm_10000_40_20.gr,0,9999,2000,NaN,0.076,45714,89003,2000,3923,...,distance-pruning,10000,200000,2000,45714,89003,168192527,28,108689,0.142
5443,random_connected_gnm_10000_50_20.gr,0,9999,2000,NaN,0.090,33340,67920,2000,3953,...,distance-pruning,10000,250000,2000,33340,67920,128071165,44,148950,0.175

In [20]:
from scipy.stats import gmean
print("K       & KM SOLVED  & KM DIJKSTRAS & KM TIME & NA SOLVED & BDA SSP & BDA SSP Fail & Iterations Success & Iterations Fail & NA Time & SPEEDUP\\\\")
for graphName, graphDf in mergedDf.groupby(by='NODES'):
    print("\midrule\n")
    print(graphName)
    print("\midrule\n")
    for pathsCount, pathsCountDf in graphDf.groupby(by='K'):
        bothSolveDf = pathsCountDf.loc[(~pathsCountDf['TIME_kurz'].isna()) & (~pathsCountDf['TIME_na'].isna())]
        bothSolveDf['SPEEDUP'] = bothSolveDf['TIME_kurz']/bothSolveDf['TIME_na']
        averageSpeedup = gmean(bothSolveDf[bothSolveDf['SPEEDUP'].notna()]['SPEEDUP'])
        #averageSpeedup = bothSolveDf[bothSolveDf['SPEEDUP'].notna()]['SPEEDUP'].mean()
        dijkstraPolls = gmean(pathsCountDf[pathsCountDf['SOLUTIONS_kurz'].notna()]['SP_TREES'])
        #print(len(pathsCountDf[pathsCountDf['TIME_na'].notna()]))
        lenNa = len(pathsCountDf[pathsCountDf['SOLUTIONS_na'].notna()])
        lenKurz = len(pathsCountDf[pathsCountDf['SOLUTIONS_kurz'].notna()])
        timeKurz = gmean(pathsCountDf[pathsCountDf['TIME_kurz'].notna()]['TIME_kurz'])
        timeNa = gmean(pathsCountDf[pathsCountDf['TIME_na'].notna()]['TIME_na'])
        bdaQueries = gmean(pathsCountDf[pathsCountDf['SOLUTIONS_na'].notna()]['BDA_QUERIES'])
        failedBdaQueries = gmean(pathsCountDf.loc[(pathsCountDf['SOLUTIONS_na'].notna()) & (pathsCountDf['FAILED_BDA']>0), 'FAILED_BDA'])
        expansionsPerSuccess = gmean(pathsCountDf[pathsCountDf['SOLUTIONS_na'].notna()]['EXPANSIONS_PER_BDA'])
        expansionsPerFail = gmean(pathsCountDf.loc[(pathsCountDf['SOLUTIONS_na'].notna()) & (pathsCountDf['FAILED_BDA']>0), 'EXPANSIONS_PER_FAILED_BDA'])
        print(f'{pathsCount:7d} &{lenKurz:10d} &{dijkstraPolls:10.0f} &{timeKurz:10.2f} &{lenNa:10} &{bdaQueries:10.0f} &{failedBdaQueries:10.0f} &{expansionsPerSuccess:20.0f} &{expansionsPerFail:20.0f} &{timeNa:10.2f} &{averageSpeedup:8.2f}\\\\')

K       & KM SOLVED  & KM DIJKSTRAS & KM TIME & NA SOLVED & BDA SSP & BDA SSP Fail & Iterations Success & Iterations Fail & NA Time & SPEEDUP\\
\midrule

2000
\midrule

    200 &       266 &         5 &      0.01 &       266 &       397 &       115 &                  16 &                   8 &      0.01 &    1.05\\
    500 &       266 &        13 &      0.02 &       266 &       996 &       291 &                  16 &                   8 &      0.02 &    1.18\\
   1000 &       266 &        26 &      0.03 &       266 &      1996 &       583 &                  16 &                   8 &      0.03 &    1.19\\
   2000 &       266 &        55 &      0.06 &       266 &      3995 &      1167 &                  16 &                   8 &      0.05 &    1.19\\
\midrule

4000
\midrule

    200 &       279 &         4 &      0.01 &       279 &       397 &       115 &                  17 &                   9 &      0.01 &    0.95\\
    500 &       279 &         9 &      0.02 &       279 &       996 &       290 &                  17 &                   9 &      0.02 &    1.12\\
   1000 &       279 &        17 &      0.04 &       279 &      1995 &       583 &                  17 &                   9 &      0.03 &    1.13\\
   2000 &       279 &        35 &      0.07 &       279 &      3994 &      1168 &                  18 &                   9 &      0.06 &    1.19\\
\midrule

6000
\midrule

    200 &       274 &         3 &      0.02 &       274 &       397 &       115 &                  18 &                   9 &      0.02 &    0.94\\
    500 &       274 &         7 &      0.03 &       274 &       997 &       292 &                  18 &                   9 &      0.02 &    1.12\\
   1000 &       274 &        13 &      0.04 &       274 &      1996 &       583 &                  18 &                   9 &      0.04 &    1.17\\
   2000 &       274 &        27 &      0.08 &       274 &      3996 &      1168 &                  18 &                   9 &      0.06 &    1.27\\
\midrule

8000
\midrule

    200 &       273 &         3 &      0.02 &       273 &       397 &       114 &                  19 &                   9 &      0.02 &    0.84\\
    500 &       273 &         5 &      0.03 &       273 &       997 &       290 &                  19 &                   9 &      0.03 &    1.10\\
   1000 &       273 &        10 &      0.05 &       273 &      1996 &       582 &                  19 &                   9 &      0.04 &    1.17\\
   2000 &       273 &        21 &      0.09 &       273 &      3996 &      1164 &                  19 &                   9 &      0.07 &    1.33\\
\midrule

10000
\midrule

    200 &       269 &         3 &      0.02 &       269 &       397 &       115 &                  19 &                  10 &      0.02 &    0.88\\
    500 &       269 &         5 &      0.04 &       269 &       997 &       290 &                  19 &                  10 &      0.03 &    1.09\\
   1000 &       269 &        10 &      0.06 &       269 &      1996 &       583 &                  19 &                  10 &      0.05 &    1.21\\
   2000 &       269 &        20 &      0.10 &       269 &      3996 &      1166 &                  19 &                  10 &      0.07 &    1.38\\