In [1]:
import pandas as pd

In [3]:
instancesHeader = ['GRAPH', 'SOURCE', 'TARGET', 'K']

instancesDf = pd.read_csv('grid_instances.csv', delimiter=' ', header=None, names=instancesHeader)
instancesDf

                     GRAPH  SOURCE  TARGET        K
0      Grid-Problem10.grid    9511    4531       10
1      Grid-Problem10.grid    7811     252       10
2      Grid-Problem10.grid    7947    1413       10
3      Grid-Problem10.grid    8415    5293       10
4      Grid-Problem10.grid    9592    7948       10
...                    ...     ...     ...      ...
17995   Grid-Problem9.grid    5017    3141  1000000
17996   Grid-Problem9.grid    2034    2397  1000000
17997   Grid-Problem9.grid    5385    7307  1000000
17998   Grid-Problem9.grid    1366    6911  1000000
17999   Grid-Problem9.grid    9209    1802  1000000

[18000 rows x 4 columns]

In [4]:
newAlgoHeader = ['ALGO', 'GRAPH', 'SOURCE', 'TARGET', 'K', 'TIME', 'COST_MIN', 'COST_MAX', 'SOLUTIONS', 'BDA_QUERIES', 'FAILED_BDA', 'EXPANSIONS_PER_BDA', 'EXPANSIONS_PER_FAILED_BDA', 'POOL_SIZE']

newAlgoDf = pd.read_csv('finalGridResults_na.csv', delimiter=';', header=None, names=newAlgoHeader)
newAlgoDf
#print(newAlgoDf[newAlgoDf['SOURCE']==55147].to_string())
#print(newAlgoDf.to_string())

,ALGO,GRAPH,SOURCE,TARGET,K,TIME,COST_MIN,COST_MAX,SOLUTIONS,BDA_QUERIES,FAILED_BDA,EXPANSIONS_PER_BDA,EXPANSIONS_PER_FAILED_BDA,POOL_SIZE
0,NaN,Grid-Problem10.grid,9511,4531,10,0.003,243,244,10,15,2,52,18,400
1,NaN,Grid-Problem10.grid,7811,252,10,0.004,369,369,10,11,0,55,0,400
2,NaN,Grid-Problem10.grid,7947,1413,10,0.002,308,309,10,11,0,47,0,400
3,NaN,Grid-Problem10.grid,8415,5293,10,0.002,349,350,10,11,0,59,0,400
4,NaN,Grid-Problem10.grid,9592,7948,10,0.002,215,216,10,15,3,32,8,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,NaN,Grid-Problem9.grid,8501,3942,1000000,10.952,257,267,1000000,1633333,244992,19,10,400
17996,NaN,Grid-Problem9.grid,8423,1287,1000000,15.925,419,426,1000000,1497327,245953,29,17,1000
17997,NaN,Grid-Problem9.grid,1369,2252,1000000,19.774,87,115,1000000,1763789,417842,14,8,9800
17998,NaN,Grid-Problem9.grid,8748,7648,1000000,36.028,52,97,1000000,1727117,360862,10,124,9800
17999,NaN,Grid-Problem9.grid,83,1500,1000000,93.808,368,376,1000000,1668187,348334,24,744,9600

In [5]:
kurzHeader = ['ALGO', 'OPTIMISTIC', 'DUMMY', 'PRUNING', 'NODES', 'ARCS', 'SOURCE' , 'TARGET', 'K', 'SOLUTIONS', 'COST_MIN', 'COST_MAX', 'SUM_OF_COSTS', 'SP_TREES', 'SP_TREES_EXPANSIONS', 'TIME']

kurzDf = pd.read_csv('finalGridResults_kurz.csv', delimiter=';', header=None, names=kurzHeader)
kurzDf

,ALGO,OPTIMISTIC,DUMMY,PRUNING,NODES,ARCS,SOURCE,TARGET,K,SOLUTIONS,COST_MIN,COST_MAX,SUM_OF_COSTS,SP_TREES,SP_TREES_EXPANSIONS,TIME
0,kurz,optimistic,NaN,distance-pruning,10000,39600,9511,4531,10,10,243,244,2438,1,8191,0.004
1,kurz,optimistic,NaN,distance-pruning,10000,39600,7811,252,10,10,369,369,3690,1,8796,0.004
2,kurz,optimistic,NaN,distance-pruning,10000,39600,7947,1413,10,10,308,309,3084,1,7017,0.004
3,kurz,optimistic,NaN,distance-pruning,10000,39600,8415,5293,10,10,349,350,3494,1,8628,0.004
4,kurz,optimistic,NaN,distance-pruning,10000,39600,9592,7948,10,10,215,216,2152,1,5928,0.003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17501,kurz,optimistic,NaN,distance-pruning,10000,39600,232,570,1000000,1000000,178,192,190736677,347617,614221686,208.988
17502,kurz,optimistic,NaN,distance-pruning,10000,39600,5385,7307,1000000,1000000,338,348,347110771,90046,77519544,199.780
17503,kurz,optimistic,NaN,distance-pruning,10000,39600,3425,6211,1000000,1000000,140,160,158006532,257298,451601188,657.431
17504,kurz,optimistic,NaN,distance-pruning,10000,39600,3464,4332,1000000,1000000,151,170,168030787,263531,398980779,560.481
17505,kurz,optimistic,NaN,distance-pruning,10000,39600,5798,5147,1000000,1000000,200,217,215265270,422192,497998532,654.479

In [6]:
mergedDf = pd.merge(instancesDf, newAlgoDf, on=['GRAPH', 'SOURCE', 'TARGET', 'K'], how='left')
mergedDf

,GRAPH,SOURCE,TARGET,K,ALGO,TIME,COST_MIN,COST_MAX,SOLUTIONS,BDA_QUERIES,FAILED_BDA,EXPANSIONS_PER_BDA,EXPANSIONS_PER_FAILED_BDA,POOL_SIZE
0,Grid-Problem10.grid,9511,4531,10,NaN,0.003,243,244,10,15,2,52,18,400
1,Grid-Problem10.grid,7811,252,10,NaN,0.004,369,369,10,11,0,55,0,400
2,Grid-Problem10.grid,7947,1413,10,NaN,0.002,308,309,10,11,0,47,0,400
3,Grid-Problem10.grid,8415,5293,10,NaN,0.002,349,350,10,11,0,59,0,400
4,Grid-Problem10.grid,9592,7948,10,NaN,0.002,215,216,10,15,3,32,8,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,Grid-Problem9.grid,5017,3141,1000000,NaN,11.324,139,160,1000000,1873879,493726,21,12,400
17996,Grid-Problem9.grid,2034,2397,1000000,NaN,6.521,253,268,1000000,1563531,211304,19,13,600
17997,Grid-Problem9.grid,5385,7307,1000000,NaN,6.789,338,348,1000000,1455747,249196,21,7,600
17998,Grid-Problem9.grid,1366,6911,1000000,NaN,13.104,352,358,1000000,1934537,559729,28,22,600
17999,Grid-Problem9.grid,9209,1802,1000000,NaN,10.725,296,307,1000000,1772811,462041,35,28,400

In [8]:
mergedDf = pd.merge(mergedDf, kurzDf, on=['SOURCE', 'TARGET', 'K'], how='left', suffixes=("_na", "_kurz"))

In [9]:
mergedDf = mergedDf.loc[mergedDf['TIME_kurz'].notna() | mergedDf['TIME_na'].notna()]
mergedDf

,GRAPH,SOURCE,TARGET,K,ALGO_na,TIME_na,COST_MIN_na,COST_MAX_na,SOLUTIONS_na,BDA_QUERIES,...,PRUNING,NODES,ARCS,SOLUTIONS_kurz,COST_MIN_kurz,COST_MAX_kurz,SUM_OF_COSTS,SP_TREES,SP_TREES_EXPANSIONS,TIME_kurz
0,Grid-Problem10.grid,9511,4531,10,NaN,0.003,243,244,10,15,...,distance-pruning,10000.0,39600.0,10.0,243.0,244.0,2438.0,1.0,8191.0,0.004
1,Grid-Problem10.grid,7811,252,10,NaN,0.004,369,369,10,11,...,distance-pruning,10000.0,39600.0,10.0,369.0,369.0,3690.0,1.0,8796.0,0.004
2,Grid-Problem10.grid,7947,1413,10,NaN,0.002,308,309,10,11,...,distance-pruning,10000.0,39600.0,10.0,308.0,309.0,3084.0,1.0,7017.0,0.004
3,Grid-Problem10.grid,8415,5293,10,NaN,0.002,349,350,10,11,...,distance-pruning,10000.0,39600.0,10.0,349.0,350.0,3494.0,1.0,8628.0,0.004
4,Grid-Problem10.grid,9592,7948,10,NaN,0.002,215,216,10,15,...,distance-pruning,10000.0,39600.0,10.0,215.0,216.0,2152.0,1.0,5928.0,0.003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,Grid-Problem9.grid,5017,3141,1000000,NaN,11.324,139,160,1000000,1873879,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17996,Grid-Problem9.grid,2034,2397,1000000,NaN,6.521,253,268,1000000,1563531,...,distance-pruning,10000.0,39600.0,1000000.0,253.0,268.0,266481448.0,248370.0,379481958.0,141.850
17997,Grid-Problem9.grid,5385,7307,1000000,NaN,6.789,338,348,1000000,1455747,...,distance-pruning,10000.0,39600.0,1000000.0,338.0,348.0,347110771.0,90046.0,77519544.0,199.780
17998,Grid-Problem9.grid,1366,6911,1000000,NaN,13.104,352,358,1000000,1934537,...,distance-pruning,10000.0,39600.0,1000000.0,352.0,358.0,357527320.0,25029.0,24292185.0,24.594
17999,Grid-Problem9.grid,9209,1802,1000000,NaN,10.725,296,307,1000000,1772811,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
import math
mergedDf.loc[(mergedDf['TIME_kurz'] < mergedDf['TIME_na']) & (mergedDf['K'] > 100), ['GRAPH', 'SOURCE', 'TARGET', 'K', 'FAILED_BDA', 'TIME_na', 'TIME_kurz', 'COST_MAX_kurz', 'COST_MAX_na', 'SP_TREES', 'FAILED_BDA', 'EXPANSIONS_PER_FAILED_BDA']]

,GRAPH,SOURCE,TARGET,K,FAILED_BDA,TIME_na,TIME_kurz,COST_MAX_kurz,COST_MAX_na,SP_TREES,FAILED_BDA,EXPANSIONS_PER_FAILED_BDA
486,Grid-Problem10.grid,6215,1300,1000,302,0.036,0.034,196.0,196,308.0,302,20
1326,Grid-Problem10.grid,8895,30,100000,50525,3.515,2.921,462.0,462,12724.0,50525,50
1526,Grid-Problem10.grid,8895,30,500000,40510,21.671,19.317,464.0,464,147554.0,40510,35
2231,Grid-Problem1.grid,9782,5600,1000,432,0.267,0.034,374.0,374,1.0,432,1845
2282,Grid-Problem1.grid,5750,11,1000,118,0.119,0.028,299.0,299,33.0,118,242
...,...,...,...,...,...,...,...,...,...,...,...,...
16977,Grid-Problem9.grid,83,1500,5000,1278,0.222,0.119,372.0,372,159.0,1278,371
17177,Grid-Problem9.grid,83,1500,10000,4291,0.734,0.303,373.0,373,999.0,4291,452
17577,Grid-Problem9.grid,83,1500,100000,27440,5.866,4.894,374.0,374,4920.0,27440,602
17777,Grid-Problem9.grid,83,1500,500000,162268,37.175,26.609,376.0,376,75072.0,162268,719
17977,Grid-Problem9.grid,83,1500,1000000,348334,93.808,33.436,376.0,376,75072.0,348334,744

In [19]:
from scipy.stats import gmean
print("K       & KM SOLVED  & KM DIJKSTRAS & KM TIME & NA SOLVED & BDA SSP & BDA SSP Fail & Iterations Success & Iterations Fail & NA Time & SPEEDUP\\\\")
print("\midrule\n")
for pathsCount, pathsCountDf in mergedDf.groupby(by='K'):
    bothSolveDf = pathsCountDf.loc[(~pathsCountDf['TIME_kurz'].isna()) & (~pathsCountDf['TIME_na'].isna())]
    bothSolveDf['SPEEDUP'] = bothSolveDf['TIME_kurz']/bothSolveDf['TIME_na']
    averageSpeedup = gmean(bothSolveDf[bothSolveDf['SPEEDUP'].notna()]['SPEEDUP'])
    #averageSpeedup = bothSolveDf[bothSolveDf['SPEEDUP'].notna()]['SPEEDUP'].mean()
    dijkstraPolls = gmean(pathsCountDf[pathsCountDf['SOLUTIONS_kurz'].notna()]['SP_TREES'])
    #print(len(pathsCountDf[pathsCountDf['TIME_na'].notna()]))
    lenNa = len(pathsCountDf[pathsCountDf['SOLUTIONS_na'].notna()])
    lenKurz = len(pathsCountDf[pathsCountDf['SOLUTIONS_kurz'].notna()])
    timeKurz = gmean(pathsCountDf[pathsCountDf['TIME_kurz'].notna()]['TIME_kurz'])
    timeNa = gmean(pathsCountDf[pathsCountDf['TIME_na'].notna()]['TIME_na'])
    bdaQueries = gmean(pathsCountDf[pathsCountDf['SOLUTIONS_na'].notna()]['BDA_QUERIES'])
    failedBdaQueries = gmean(pathsCountDf.loc[(pathsCountDf['SOLUTIONS_na'].notna()) & (pathsCountDf['FAILED_BDA']>0), 'FAILED_BDA'])
    expansionsPerSuccess = gmean(pathsCountDf[pathsCountDf['SOLUTIONS_na'].notna()]['EXPANSIONS_PER_BDA'])
    expansionsPerFail = gmean(pathsCountDf.loc[(pathsCountDf['SOLUTIONS_na'].notna()) & (pathsCountDf['FAILED_BDA']>0), 'EXPANSIONS_PER_FAILED_BDA'])
    print(f'{pathsCount:7d} &{lenKurz:10d} &{dijkstraPolls:10.0f} &{timeKurz:10.2f} &{lenNa:10} &{bdaQueries:10.0f} &{failedBdaQueries:10.0f} &{expansionsPerSuccess:20.0f} &{expansionsPerFail:20.0f} &{timeNa:10.2f} &{averageSpeedup:8.2f}\\\\')

K       & KM SOLVED  & KM DIJKSTRAS & KM TIME & NA SOLVED & BDA SSP & BDA SSP Fail & Iterations Success & Iterations Fail & NA Time & SPEEDUP\\
\midrule

     10 &      2000 &         1 &      0.00 &      2000 &        12 &         3 &                  37 &                  23 &      0.00 &    0.00\\
    100 &      2000 &         5 &      0.01 &      2000 &       153 &        21 &                  33 &                  19 &      0.00 &    2.32\\
   1000 &      2000 &        97 &      0.05 &      2000 &      1604 &       245 &                  28 &                  17 &      0.01 &    3.68\\
   5000 &      2000 &       778 &      0.25 &      2000 &      8182 &      1303 &                  25 &                  17 &      0.05 &    4.66\\
  10000 &      2000 &      1847 &      0.53 &      2000 &     16387 &      2656 &                  25 &                  16 &      0.10 &    5.17\\
  50000 &      2000 &     11207 &      4.82 &      2000 &     82481 &     13541 &                  23 &                  16 &      0.49 &    9.76\\
 100000 &      2000 &     24011 &      9.95 &      2000 &    167223 &     28760 &                  22 &                  16 &      1.03 &    9.70\\
 500000 &      1951 &    130124 &     58.02 &      2000 &    836001 &    142677 &                  21 &                  16 &      6.16 &    9.78\\
1000000 &      1555 &    220368 &     95.47 &      2000 &   1681693 &    291944 &                  20 &                  16 &     12.19 &    9.11\\

/tmp/ipykernel_1824871/714146239.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bothSolveDf['SPEEDUP'] = bothSolveDf['TIME_kurz']/bothSolveDf['TIME_na']

In [73]:
mergedDf[mergedDf['GRAPH'].str.contains('CTR')]

,GRAPH,SOURCE,TARGET,K,ALGO_na,TIME_na,COST_MIN_na,COST_MAX_na,SOLUTIONS_na,BDA_QUERIES,...,NODES,ARCS,SOLUTIONS_kurz,COST_MIN_kurz,COST_MAX_kurz,SUM_OF_COSTS,SP_TREES,SP_TREES_EXPANSIONS,TIME_kurz,SPEEDUP
5400,USA-road-dt.CTR.gr,12181763,10663437,10,NaN,7200.0,NaN,NaN,NaN,NaN,...,14081816.0,34292496.0,10.0,1268594.0,1268594.0,12685940.0,1.0,168979.0,1.627,0.000226
5401,USA-road-dt.CTR.gr,13263609,3512051,10,NaN,7200.0,NaN,NaN,NaN,NaN,...,14081816.0,34292496.0,10.0,5474977.0,5474977.0,54749770.0,1.0,3856891.0,3.875,0.000538
5402,USA-road-dt.CTR.gr,8617129,2921811,10,NaN,7200.0,NaN,NaN,NaN,NaN,...,14081816.0,34292496.0,10.0,8888964.0,8888964.0,88889640.0,1.0,7897146.0,7.238,0.001005
5403,USA-road-dt.CTR.gr,13145916,309892,10,NaN,7200.0,NaN,NaN,NaN,NaN,...,14081816.0,34292496.0,10.0,12879745.0,12879745.0,128797450.0,1.0,10634038.0,8.625,0.001198
5404,USA-road-dt.CTR.gr,10923367,8213275,10,NaN,7200.0,NaN,NaN,NaN,NaN,...,14081816.0,34292496.0,10.0,3839849.0,3839849.0,38398490.0,1.0,1862878.0,1.920,0.000267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7195,USA-road-dt.CTR.gr,628005,7120819,1000000,NaN,7200.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7200.000,1.000000
7196,USA-road-dt.CTR.gr,7228136,11312825,1000000,NaN,7200.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7200.000,1.000000
7197,USA-road-dt.CTR.gr,4648576,7370601,1000000,NaN,7200.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7200.000,1.000000
7198,USA-road-dt.CTR.gr,9644393,10542969,1000000,NaN,7200.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7200.000,1.000000
7199,USA-road-dt.CTR.gr,3558135,10857567,1000000,NaN,7200.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7200.000,1.000000